# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 10:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30)),
                ('score', models.IntegerField(blank=True, default=0, null=True)),
                ('name1', models.CharField(blank=True, max_length=30)),
                ('name2', models.CharField(blank=True, max_length=30, null=True)),
                ('contact', models.IntegerField(blank=True)),
                ('college', models.CharField(blank=True, max_length=50)),
                ('reciept', models.IntegerField(blank=True)),
                ('skip', models.IntegerField(default=2)),
                ('count', models.IntegerField(default=0)),
                ('start', models.DateTimeField(default=datetime.datetime(2017, 2, 25, 10, 7, 28, 138190, tzinfo=utc))),
                ('end', models.DateTimeField()),
                ('access', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Qattempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Qrecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=500)),
                ('snipphet', models.TextField(max_length=500)),
                ('answer1', models.TextField(max_length=30)),
                ('answer2', models.TextField(max_length=30)),
                ('answer3', models.TextField(max_length=30)),
                ('answer4', models.TextField(max_length=30)),
                ('correct', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='qattempt',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mcq.Qrecord'),
        ),
        migrations.AddField(
            model_name='qattempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mcq.Profile'),
        ),
    ]
