# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 10:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mcq', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qattempt',
            old_name='user',
            new_name='User',
        ),
        migrations.AlterField(
            model_name='profile',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 25, 10, 30, 56, 786030, tzinfo=utc)),
        ),
    ]
