# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq', '0006_auto_20170228_1328'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeniorQrecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=500)),
                ('snipphet', models.TextField(max_length=500)),
                ('answer1', models.TextField(max_length=30)),
                ('answer2', models.TextField(max_length=30)),
                ('answer3', models.TextField(max_length=30)),
                ('answer4', models.TextField(max_length=30)),
                ('correct', models.IntegerField()),
            ],
        ),
    ]
