# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 14:35
from __future__ import unicode_literals

from django.db import migrations, models
import mcq.models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq', '0007_seniorqrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qattempt',
            name='attempt',
            field=models.ForeignKey(on_delete=mcq.models.SeniorQrecord, to='mcq.Qrecord'),
        ),
    ]
