# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 14:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mcq', '0008_auto_20170228_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeniorQattempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_count', models.IntegerField(default=0)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mcq.SeniorQrecord')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mcq.Profile')),
            ],
        ),
    ]
