# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq', '0009_seniorqattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='skipscoreadded',
            field=models.IntegerField(default=0),
        ),
    ]
