# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq', '0010_profile_skipscoreadded'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='correct_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='wrong_count',
            field=models.IntegerField(default=0),
        ),
    ]
