# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq', '0011_auto_20170315_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='contact',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
