# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq', '0012_auto_20170319_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrecord',
            name='answer1',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='qrecord',
            name='answer2',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='qrecord',
            name='answer3',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='qrecord',
            name='answer4',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='seniorqrecord',
            name='answer1',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='seniorqrecord',
            name='answer2',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='seniorqrecord',
            name='answer3',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='seniorqrecord',
            name='answer4',
            field=models.TextField(max_length=100),
        ),
    ]
